# Generated by Django 6.0.4 on 2026-04-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_radicals_learned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_vocab_learned',
            field=models.IntegerField(default=0),
        ),
    ]
