# Generated by Django 6.0.4 on 2026-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='is_learned',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='srs_stage',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='tier',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master'), ('infinite', 'Infinite')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='tier_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='learningitem',
            name='item_type',
            field=models.CharField(choices=[('radical', 'Radical'), ('kanji', 'Kanji'), ('hiragana', 'Hiragana'), ('katakana', 'Katakana'), ('vocabulary', 'Vocabulary')], max_length=20),
        ),
    ]
